"""Added app size for app table

Revision ID: 033f0139ec8f
Revises: 396cf45a377c
Create Date: 2022-02-10 14:32:39.811457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033f0139ec8f'
down_revision = '396cf45a377c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rankingapp', sa.Column('installsize', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rankingapp', 'installsize')
    # ### end Alembic commands ###
