"""Added reviews and download for apps

Revision ID: 396cf45a377c
Revises: ea6e6b104b78
Create Date: 2022-02-09 16:03:22.805415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396cf45a377c'
down_revision = 'ea6e6b104b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rankingapp', sa.Column('installs', sa.Integer(), nullable=True))
    op.add_column('rankingapp', sa.Column('ratings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rankingapp', 'ratings')
    op.drop_column('rankingapp', 'installs')
    # ### end Alembic commands ###
