"""Added searchkey locale

Revision ID: ea6e6b104b78
Revises:
Create Date: 2022-01-31 15:10:23.763511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6e6b104b78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searchkey', sa.Column('locale', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searchkey', 'locale')
    # ### end Alembic commands ###
