"""adding the app version

Revision ID: eece3361687d
Revises: 2e614e6efefc
Create Date: 2022-02-13 00:17:58.684919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eece3361687d'
down_revision = '2e614e6efefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
